### ISSUE TITLE
请问怎么使用“CryFont”？只运行成功了“Font”，而“CryFont”都没办法加入插件

### ISSUE THREAD

**Issue by kakaluote123666** [Nihility-Protoss/XierluoEPUB_Sigil#1]
请问可以简单指导一下吗？感谢

**Comment by Nihility-Protoss** [comment]
CryFont仅为插件部分，未包含所有依赖项，需要自行pip install对应依赖

**Comment by kakaluote123666** [comment]
好的，谢谢你，虽然我不懂这个东西



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nihility-Protoss/XierluoEPUB_Sigil] 请问怎么使用“CryFont”？只运行成功了“Font”，而“CryFont”都没办法加入插件 (Issue #1)




 
CryFont仅为插件部分，未包含所有依赖项，需要自行pip install对应依赖

**Comment by kakaluote123666** [comment]
> CryFont 框架插件部分，未包含所有依赖项，需要自行pip install对应依赖项

感谢 插件安装的问题已经解决了
