### ISSUE TITLE
更换模板字体相关问题 & Bug: css link error

### ISSUE THREAD

**Issue by ghost** [Nihility-Protoss/XierluoEPUB_Sigil#3]
可不可以只把字编成“&#x????;”不变成“甒徿”什么的，虽然这样混得更乱，但整本书都只能使用那个预设的那个字体，阅读大打折扣，而且还改不了

**Comment by Nihility-Protoss** [comment]
releases的zip中有一个ttf文件，那个文件就是默认的模板字体文件，你可以将这个文件替换成任意字体文件
建议：新的字体文件能够达到和默认模板字体文件相近的文本覆盖率

**Comment by Nihility-Protoss** [comment]
**Regarding your suggestion**
“&#x????;”形态确实可以表示字体，但是我不确定这种形态能否顺利使用css进行字体上的替换，由于本插件是基于ttf的映射表替换实现的，本人对html-css-ttf的替换逻辑了解不足，故放弃了使用这种形态。
如果您有更好的代码实现建议，可以提交pr进行交流。

**Comment by ghost** [comment]
感谢解答，发现修改字体名字后，&amp;#x????会自动变回生僻字，所以我说的那个就没有意义了。主要是这个字体，全书只能使用一个字体，只混淆某个html的话弄其他设置也挺麻烦的，请问有其他地方下载与默认字体文件覆盖率相似的字体吗？其实最常见的最好，没有任何特点就是特点






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Nihility-Protoss/XierluoEPUB_Sigil] 字体 (Issue #3)




 
Regarding your suggestion
 “&amp;#x????;”形态确实可以表示字体，但是我不确定这种形态能否顺利使用css进行字体上的替换，由于本插件是基于ttf的映射表替换实现的，本人对html-css-ttf的替换逻辑了解不足，故放弃了使用这种形态。
 如果您有更好的代码实现建议，可以提交pr进行交流。

**Comment by Nihility-Protoss** [comment]
**只混淆某个html**
从Sigil的插件设计上来说，是可以对不同的html进行处理的，但是如果允许使用者选择不同的html进行处理，那么我需要做一个相应的py-gui，我对这方面的研究严重不足，可能需要一段时间后才能更新完成这个插件。

**下载字体文件**
这个我没什么好的建议，如果windwos默认的那堆字体中有能够符合您的需求的，您可以在C:\Windows\Fonts文件夹下找到相应的ttf文件，这些文件一般来说都是符合文本覆盖率上的需求的

**Comment by ghost** [comment]
从预览器来看，我在其他很多地方下载的字体大多数是第一张图的样子，windwos上的也是。而预设的这样的非常少(看图片像是有换行)，如果替换的话，会显示运行失败。






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Nihility-Protoss/XierluoEPUB_Sigil] 字体 (Issue #3)




 
只混淆某个html
 从Sigil的插件设计上来说，是可以对不同的html进行处理的，但是如果允许使用者选择不同的html进行处理，那么我需要做一个相应的py-gui，我对这方面的研究严重不足，可能需要一段时间后才能更新完成这个插件。
 
下载字体文件
 这个我没什么好的建议，如果windwos默认的那堆字体中有能够符合您的需求的，您可以在C:\Windows\Fonts文件夹下找到相应的ttf文件，这些文件一般来说都是符合文本覆盖率上的需求的

**Comment by ghost** [comment]
2.1混淆后显示不了正常字，没有修改任何设置，那个main里面也没字体，放在多看上也还是显示是生僻字。修改插件plugin.xml中名称和文件夹名称，会显示同名，或者不是一个有效的插件




另外一个大章带id地址的小章也会被混淆这样就跳不了目录了。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Nihility-Protoss/XierluoEPUB_Sigil] 字体 (Issue #3)




 
只混淆某个html
 从Sigil的插件设计上来说，是可以对不同的html进行处理的，但是如果允许使用者选择不同的html进行处理，那么我需要做一个相应的py-gui，我对这方面的研究严重不足，可能需要一段时间后才能更新完成这个插件。
 
下载字体文件
 这个我没什么好的建议，如果windwos默认的那堆字体中有能够符合您的需求的，您可以在C:\Windows\Fonts文件夹下找到相应的ttf文件，这些文件一般来说都是符合文本覆盖率上的需求的

**Comment by Nihility-Protoss** [comment]
**bug**
我测试的时候一切正常来着……有完整的bug信息吗？或者混淆后无法显示正常字的epub？
印象中是做了多看的适配的，不过用的方法好像有点邪道，我需要去确定一下当时怎么做的适配。

**大章带id地址的小章**
这个问题暂时没想好怎么解决，sigil的epublib解析出来的python结构体似乎没法展示下层文件，我手上也难找到有类似结构的epub文件

**Comment by ghost** [comment]
[1.zip](https://github.com/user-attachments/files/16657959/1.zip)
同个文件用两个版本的混淆

**Comment by Nihility-Protoss** [comment]
**Bug analysis**
我知道了，测试得到如下link能链接到正确的css文件
_<link href="../Styles/OThULCurSAMvcOqPPApLSApZMgMGKaw.css" rel="stylesheet" type="text/css"/>_

在您给出的epub文件样本中，使用的css文件夹名称为**Styles**，而在我的大多数测试用例中，该文件夹名称为`style`，因此在生成link时使用的是硬编码，因此导致了这个bug

我将会在v2.2中修复这个bug
